export const carBrands = [
    { label: "Chevrolet", value: "chevrolet" },
    { label: "Kia", value: "kia" },
    { label: "Toyota", value: "toyota" },
    { label: "Hyundai", value: "hyundai" },
    { label: "Chery", value: "chery" },
    { label: "Suzuki", value: "suzuki" },
    { label: "Renault", value: "renault" },
    { label: "GWM", value: "gwm" },
    { label: "JAC", value: "jac" },
    { label: "DFSK", value: "dfsk" },
    { label: "Volkswagen", value: "volkswagen" },
    { label: "Nissan", value: "nissan" },
    { label: "Hino", value: "hino" },
    { label: "Mazda", value: "mazda" },
    { label: "Shineray", value: "shineray" },
    { label: "Dongfeng", value: "dongfeng" },
    { label: "Sinotruk", value: "sinotruk" },
    { label: "Jetour", value: "jetour" },
    { label: "Ford", value: "ford" },
    { label: "Changan", value: "changan" },
    { label: "BMW", value: "bmw" },
    { label: "Mercedes-Benz", value: "mercedes_benz" },
    { label: "Audi", value: "audi" },
    { label: "Lexus", value: "lexus" },
    { label: "Jeep", value: "jeep" },
    { label: "Porsche", value: "porsche" },
    { label: "Volvo", value: "volvo" },
    { label: "Jaguar", value: "jaguar" },
    { label: "Ferrari", value: "ferrari" },
    { label: "Lamborghini", value: "lamborghini" },
    { label: "Mitsubishi", value: "mitsubishi" },
    { label: "Peugeot", value: "peugeot" },
    { label: "Fiat", value: "fiat" },
    { label: "Land Rover", value: "land_rover" },
    { label: "BYD", value: "byd" },
    { label: "Subaru", value: "subaru" },
    { label: "Citroën", value: "citroen" },
    { label: "Bentley", value: "bentley" },
    { label: "Mini", value: "mini" },
    { label: "Rolls-Royce", value: "rolls_royce" },
    { label: "Aston Martin", value: "aston_martin" },
    { label: "Lancia", value: "lancia" },
    { label: "Otros", value: "others" },
  ];
  export const motorcycleBrands = [
    { label: "Shineray", value: "shineray" },
    { label: "Daytona", value: "daytona" },
    { label: "IGM", value: "igm" },
    { label: "Ranger", value: "ranger" },
    { label: "Bajaj", value: "bajaj" },
    { label: "Suzuki", value: "suzuki" },
    { label: "Tuko", value: "tuko" },
    { label: "Yamaha", value: "yamaha" },
    { label: "Motor one", value: "motor_one" },
    { label: "Loncin", value: "loncin" },
    { label: "Honda", value: "honda" },
    { label: "Pulsar", value: "pulsar" },
    { label: "Sukida", value: "sukida" },
    { label: "Thunder", value: "thunder" },
    { label: "Tundra", value: "tundra" },
    { label: "Bultaco", value: "bultaco" },
    { label: "SHM", value: "shm" },
    { label: "DNA Motors", value: "dna_motors" },
    { label: "Lifan", value: "lifan" },
    { label: "Montesa", value: "montesa" },
    { label: "TVS", value: "tvs" },
    { label: "AXXO", value: "axxo" },
    { label: "Factory Bike", value: "factory_bike" },
    { label: "Benelli", value: "benelli" },
    { label: "Otros", value: "others" },
];
  